#!/usr/bin/env bash
redis-server &
while IFS= read -r line; do
  if (echo "$line" | redis-cli -x -e); then
    sleep 1s
  else
    echo "Error executing: ${line}"
  fi
done <redisscripts.txt
sha="$(echo "SCRIPT LOAD \"return 'Immabe a cached script'\"" |
  redis-cli -x -e)"
echo "$sha"
echo "EVALSHA ${sha} 0" | redis-cli -x -e
echo "EVALSHA ffffffffffffffffffffffffffffffffffffffff 0" | redis-cli -x -e
redis-cli shutdown
